# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3653abbded787718ba3c790202ffd69e893cc7557bea4eabe179a3d4d153b438a70dff6354a06dbfcfeb54a2c2ca676b554a984712ecb37dcf91f2d71025c88f

test:
  secret_key_base: 01d027c71c3e47e18bf3722351f8b19636efc97eb5d8c79e2d9c5064745c606570ccc99454ed7decef654e5e625897f1d721843aaa8a65087f092279a882c80c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

